services:
  - type: web
    name: todo-backend
    runtime: node
    plan: free
    region: singapore
    branch: main

    buildCommand: npm install && npm run build && npx prisma migrate deploy
    startCommand: npm start

    healthCheckPath: /health

    envVars:
      - key: NODE_ENV
        value: production

      - key: DATABASE_URL
        sync: false

      - key: CORS_ORIGIN
        sync: false